package com.harleytg.puppyclicker

import android.os.SystemClock
import androidx.compose.animation.core.LinearEasing
import androidx.compose.animation.core.RepeatMode
import androidx.compose.animation.core.animateFloat
import androidx.compose.animation.core.infiniteRepeatable
import androidx.compose.animation.core.rememberInfiniteTransition
import androidx.compose.animation.core.tween
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.background
import androidx.compose.foundation.gestures.awaitEachGesture
import androidx.compose.foundation.gestures.awaitFirstDown
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxHeight
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.DisposableEffect
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableLongStateOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.geometry.Rect
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.Path
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.drawscope.clipPath
import androidx.compose.ui.input.pointer.pointerInput
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.Dialog
import androidx.compose.ui.window.DialogProperties
import androidx.lifecycle.Lifecycle
import androidx.lifecycle.LifecycleEventObserver
import androidx.lifecycle.compose.LocalLifecycleOwner
import com.harleytg.puppyclicker.ui.theme.LocalPuppyReducedMotion
import java.util.Locale
import kotlinx.coroutines.delay

/**
 * Destructive Settings actions all share the same uninterrupted hold requirement.
 * The timing contract and its Compose UI live together here instead of being generated by a Python patch.
 */
enum class DangerZoneAction(
    val key: String,
    val title: String,
    val description: String,
    val buttonLabel: String,
    val holdDurationMs: Long = 10_000L
) {
    RESET_SETTINGS(
        key = "settings",
        title = "Reset settings?",
        description = "Theme, accent, motion, UI scale and gameplay preference switches return to defaults. Your profile, birthday and game progress remain.",
        buttonLabel = "Hold to Reset Settings"
    ),
    RESET_PROGRESS(
        key = "progress",
        title = "Reset game progress?",
        description = "This resets the current run without awarding prestige points. Permanent prestige skills and existing special puppy unlocks remain.",
        buttonLabel = "Hold to Reset Progress"
    ),
    ERASE_ALL_DATA(
        key = "delete",
        title = "Delete local save data?",
        description = "This deletes local game progress, player identity, birthday/setup state, PupEye local integrity history and the device save mirror. Puppy Clicker will restart into first-run setup.",
        buttonLabel = "Hold to Delete Local Data"
    );

    companion object {
        fun fromKey(key: String): DangerZoneAction? = entries.firstOrNull { it.key == key }
    }
}

object DangerHoldConfirmation {
    const val HOLD_DURATION_MS = 10_000L

    fun progress(startedAtMs: Long?, nowMs: Long, durationMs: Long = HOLD_DURATION_MS): Float {
        if (startedAtMs == null || durationMs <= 0L || nowMs <= startedAtMs) return 0f
        return ((nowMs - startedAtMs).toFloat() / durationMs.toFloat()).coerceIn(0f, 1f)
    }

    fun remainingMs(startedAtMs: Long?, nowMs: Long, durationMs: Long = HOLD_DURATION_MS): Long {
        if (startedAtMs == null) return durationMs.coerceAtLeast(0L)
        return (durationMs - (nowMs - startedAtMs)).coerceAtLeast(0L)
    }

    fun isComplete(startedAtMs: Long?, nowMs: Long, durationMs: Long = HOLD_DURATION_MS): Boolean =
        startedAtMs != null && durationMs > 0L && nowMs - startedAtMs >= durationMs
}

@Composable
internal fun DangerHoldConfirmationDialog(
    action: DangerZoneAction,
    onDismiss: () -> Unit,
    onConfirmed: () -> Unit
) {
    val context = androidx.compose.ui.platform.LocalContext.current
    val lifecycleOwner = LocalLifecycleOwner.current
    val reducedMotion = LocalPuppyReducedMotion.current
    var holdStartedAtMs by remember(action.key) { mutableStateOf<Long?>(null) }
    var nowMs by remember(action.key) { mutableLongStateOf(SystemClock.elapsedRealtime()) }

    val progress = DangerHoldConfirmation.progress(holdStartedAtMs, nowMs, action.holdDurationMs)
    val remainingMs = DangerHoldConfirmation.remainingMs(holdStartedAtMs, nowMs, action.holdDurationMs)
    val countdown = String.format(Locale.US, "%.1f", remainingMs / 1000.0)

    val borderAnimation = rememberInfiniteTransition(label = "danger-border")
    val animatedBorderAlpha by borderAnimation.animateFloat(
        initialValue = 0.88f,
        targetValue = 1f,
        animationSpec = infiniteRepeatable(
            animation = tween(durationMillis = 700),
            repeatMode = RepeatMode.Reverse
        ),
        label = "danger-border-alpha"
    )
    val borderAlpha = if (reducedMotion) 1f else animatedBorderAlpha

    val stripeShift by borderAnimation.animateFloat(
        initialValue = 0f,
        targetValue = 1f,
        animationSpec = infiniteRepeatable(
            animation = tween(durationMillis = 900, easing = LinearEasing),
            repeatMode = RepeatMode.Restart
        ),
        label = "danger-stripe-shift"
    )

    fun cancelHold() {
        holdStartedAtMs = null
        nowMs = SystemClock.elapsedRealtime()
    }

    DisposableEffect(lifecycleOwner, action.key) {
        val observer = LifecycleEventObserver { _, event ->
            if (event == Lifecycle.Event.ON_PAUSE || event == Lifecycle.Event.ON_STOP) {
                cancelHold()
            }
        }
        lifecycleOwner.lifecycle.addObserver(observer)
        onDispose {
            lifecycleOwner.lifecycle.removeObserver(observer)
            cancelHold()
        }
    }

    LaunchedEffect(holdStartedAtMs, action.key) {
        val startedAt = holdStartedAtMs ?: return@LaunchedEffect
        while (holdStartedAtMs == startedAt) {
            val current = SystemClock.elapsedRealtime()
            nowMs = current
            if (DangerHoldConfirmation.isComplete(startedAt, current, action.holdDurationMs)) {
                holdStartedAtMs = null
                PuppyHaptics.perform(
                    view = null,
                    context = context,
                    event = PuppyHapticEvent.DANGER_CONFIRM,
                    enabled = true
                )
                onConfirmed()
                break
            }
            delay(16L)
        }
    }

    Dialog(
        onDismissRequest = {
            cancelHold()
            onDismiss()
        },
        properties = DialogProperties(
            dismissOnBackPress = true,
            dismissOnClickOutside = false,
            usePlatformDefaultWidth = false
        )
    ) {
        Box(Modifier.fillMaxSize()) {
            // Preserve the live Puppy Clicker screen behind the alert.
            Box(
                Modifier
                    .fillMaxSize()
                    .background(MaterialTheme.colorScheme.scrim.copy(alpha = 0.52f))
            )

            // One-piece animated red/black construction-tape frame.
            //
            // The border is a single even-odd perimeter mask. One diagonal stripe
            // field is clipped through that mask, so the pattern continues through
            // every corner without four independently drawn strips overlapping.
            Canvas(Modifier.fillMaxSize()) {
                val frame = 18.dp.toPx()
                val stripePeriod = 38.dp.toPx()
                val redStripeWidth = 20.dp.toPx()
                val travel = if (reducedMotion) 0f else stripeShift * stripePeriod
                val red = Color(0xFFE01818).copy(alpha = borderAlpha)

                val perimeter = Path().apply {
                    fillType = PathFillType.EvenOdd
                    addRect(Rect(0f, 0f, size.width, size.height))
                    addRect(
                        Rect(
                            frame,
                            frame,
                            (size.width - frame).coerceAtLeast(frame),
                            (size.height - frame).coerceAtLeast(frame)
                        )
                    )
                }

                clipPath(perimeter) {
                    // Black is the continuous tape backing.
                    drawRect(Color.Black)

                    // Draw one global 45-degree stripe field. Because the same lines
                    // pass through the full perimeter mask, all four corners join
                    // cleanly and animate as one piece.
                    var diagonal = -size.height - stripePeriod + travel
                    val end = size.width + size.height + stripePeriod
                    while (diagonal < end) {
                        drawLine(
                            color = red,
                            start = Offset(diagonal - size.height, size.height),
                            end = Offset(diagonal, 0f),
                            strokeWidth = redStripeWidth
                        )
                        diagonal += stripePeriod
                    }
                }
            }

            Box(
                modifier = Modifier
                    .fillMaxSize()
                    .padding(20.dp),
                contentAlignment = Alignment.Center
            ) {
                Surface(
                    modifier = Modifier.fillMaxWidth(0.94f),
                    shape = RoundedCornerShape(24.dp),
                    color = MaterialTheme.colorScheme.surface,
                    tonalElevation = 10.dp,
                    shadowElevation = 14.dp
                ) {
                    Column(Modifier.padding(20.dp)) {
                        Text(
                            "⚠️ DANGER ZONE",
                            style = MaterialTheme.typography.labelLarge,
                            fontWeight = FontWeight.Black,
                            color = MaterialTheme.colorScheme.error
                        )
                        Spacer(Modifier.height(7.dp))
                        Text(
                            action.title,
                            style = MaterialTheme.typography.headlineSmall,
                            fontWeight = FontWeight.Black
                        )
                        Spacer(Modifier.height(8.dp))
                        Text(action.description, style = MaterialTheme.typography.bodyMedium)
                        Spacer(Modifier.height(10.dp))
                        Text(
                            "Do you wish to continue? Press and hold the red button for 10 seconds. Releasing, moving off the button, or leaving the app cancels the hold.",
                            style = MaterialTheme.typography.bodySmall,
                            color = MaterialTheme.colorScheme.onSurfaceVariant
                        )
                        Spacer(Modifier.height(16.dp))

                        Surface(
                            modifier = Modifier
                                .fillMaxWidth()
                                .height(68.dp)
                                .pointerInput(action.key) {
                                    awaitEachGesture {
                                        val down = awaitFirstDown(requireUnconsumed = false)
                                        val pointerId = down.id
                                        val startedAt = SystemClock.elapsedRealtime()
                                        holdStartedAtMs = startedAt
                                        nowMs = startedAt
                                        var active = true

                                        while (active) {
                                            val event = awaitPointerEvent()
                                            val change = event.changes.firstOrNull { it.id == pointerId }
                                            if (change == null) {
                                                active = false
                                                if (holdStartedAtMs == startedAt) cancelHold()
                                                continue
                                            }

                                            val inside =
                                                change.position.x >= 0f &&
                                                change.position.y >= 0f &&
                                                change.position.x <= size.width.toFloat() &&
                                                change.position.y <= size.height.toFloat()

                                            active = change.pressed && inside
                                            if (!active && holdStartedAtMs == startedAt) cancelHold()
                                            change.consume()
                                        }
                                    }
                                },
                            shape = RoundedCornerShape(18.dp),
                            color = MaterialTheme.colorScheme.error
                        ) {
                            Box(Modifier.fillMaxSize()) {
                                if (progress > 0f) {
                                    Surface(
                                        modifier = Modifier
                                            .fillMaxHeight()
                                            .fillMaxWidth(progress.coerceIn(0f, 1f)),
                                        color = MaterialTheme.colorScheme.onError.copy(alpha = 0.24f)
                                    ) {}
                                }

                                Column(
                                    modifier = Modifier
                                        .fillMaxSize()
                                        .padding(horizontal = 14.dp),
                                    horizontalAlignment = Alignment.CenterHorizontally,
                                    verticalArrangement = Arrangement.Center
                                ) {
                                    Text(
                                        if (holdStartedAtMs == null) {
                                            action.buttonLabel
                                        } else {
                                            "KEEP HOLDING · ${countdown}s"
                                        },
                                        color = MaterialTheme.colorScheme.onError,
                                        fontWeight = FontWeight.Black
                                    )
                                    Text(
                                        if (holdStartedAtMs == null) {
                                            "Hold continuously for 10 seconds"
                                        } else {
                                            "${(progress * 100).toInt()}% complete"
                                        },
                                        color = MaterialTheme.colorScheme.onError.copy(alpha = 0.86f),
                                        style = MaterialTheme.typography.labelSmall
                                    )
                                }
                            }
                        }

                        Spacer(Modifier.height(10.dp))
                        OutlinedButton(
                            onClick = {
                                cancelHold()
                                onDismiss()
                            },
                            modifier = Modifier.fillMaxWidth()
                        ) {
                            Text("Cancel")
                        }
                    }
                }
            }
        }
    }
}
