package com.harleytg.puppyclicker

import java.security.SecureRandom
import org.json.JSONArray
import org.json.JSONObject

internal data class PuppyPlinkoOutcome(
    val pathRight: List<Boolean>,
    val bounceJitterPermille: List<Int>,
    val binIndex: Int,
    val multiplierHundredths: Int,
    val payoutTreats: Long
) {
    val multiplierLabel: String
        get() = if (multiplierHundredths % 100 == 0) {
            (multiplierHundredths / 100).toString() + "×"
        } else {
            (multiplierHundredths / 100.0).toString().trimEnd('0').trimEnd('.') + "×"
        }
}

internal enum class PuppyPlinkoStartFailure {
    INVALID_WAGER,
    TRANSACTION_REJECTED,
    OUTCOME_GENERATION_FAILED,
    OUTCOME_COMMIT_FAILED
}

internal data class PuppyPlinkoStartResult(
    val success: Boolean,
    val roundId: String? = null,
    val outcome: PuppyPlinkoOutcome? = null,
    val failure: PuppyPlinkoStartFailure? = null,
    val transactionFailure: PuppyCasinoTransactionFailure? = null
)

internal object PuppyPlinkoEngine {
    const val ROWS = 8
    const val BIN_COUNT = ROWS + 1
    const val MIN_WAGER_TREATS = 20L
    const val MAX_WAGER_TREATS = 100_000L
    const val WAGER_INCREMENT_TREATS = 20L
    const val PUBLISHED_RTP_PERCENT = "97.3%"

    // Visual jitter is generated by the engine too, so each committed drop can look
    // different while never changing which physical left/right decisions were rolled.
    const val MAX_BOUNCE_JITTER_PERMILLE = 220

    val wagerPresets: List<Long> = listOf(20L, 100L, 500L, 2_500L)

    // Binomial 8-row board. Eight independent 50/50 decisions naturally produce
    // nine pockets with the center pockets occurring more often, like physical Plinko.
    // The payout table keeps the published 97.3% RTP.
    val binMultiplierHundredths: List<Int> =
        listOf(5, 25, 50, 100, 150, 100, 50, 25, 5)

    init {
        require(binMultiplierHundredths.size == BIN_COUNT)
    }

    fun isValidWager(wagerTreats: Long): Boolean =
        wagerTreats in MIN_WAGER_TREATS..MAX_WAGER_TREATS &&
            wagerTreats % WAGER_INCREMENT_TREATS == 0L

    /**
     * Generates a completely fresh Plinko drop.
     *
     * Every row is an independent cryptographically secure 50/50 left/right roll.
     * The final pocket is not selected separately: it emerges from those eight rolls.
     * Extra secure-random bounce jitter is committed with the path for visual variety.
     */
    fun randomDrop(
        wagerTreats: Long,
        random: SecureRandom = SecureRandom()
    ): PuppyPlinkoOutcome {
        require(isValidWager(wagerTreats))

        val path = buildList(ROWS) {
            repeat(ROWS) {
                add(random.nextBoolean())
            }
        }
        val jitter = buildList(ROWS) {
            repeat(ROWS) {
                add(
                    random.nextInt(MAX_BOUNCE_JITTER_PERMILLE * 2 + 1) -
                        MAX_BOUNCE_JITTER_PERMILLE
                )
            }
        }

        return outcomeForPath(
            wagerTreats = wagerTreats,
            pathRight = path,
            bounceJitterPermille = jitter
        )
    }

    fun outcomeForPath(
        wagerTreats: Long,
        pathRight: List<Boolean>,
        bounceJitterPermille: List<Int> = List(ROWS) { 0 }
    ): PuppyPlinkoOutcome {
        require(isValidWager(wagerTreats))
        require(pathRight.size == ROWS)
        require(bounceJitterPermille.size == ROWS)
        require(
            bounceJitterPermille.all {
                it in -MAX_BOUNCE_JITTER_PERMILLE..MAX_BOUNCE_JITTER_PERMILLE
            }
        )

        // Each right bounce moves one pocket to the right; therefore the number
        // of right bounces is the physical landing pocket.
        val binIndex = pathRight.count { it }
        require(binIndex in 0 until BIN_COUNT)

        val multiplier = binMultiplierHundredths[binIndex]
        val payout = wagerTreats * multiplier.toLong() / 100L

        return PuppyPlinkoOutcome(
            pathRight = pathRight.toList(),
            bounceJitterPermille = bounceJitterPermille.toList(),
            binIndex = binIndex,
            multiplierHundredths = multiplier,
            payoutTreats = payout
        )
    }
}

internal object PuppyPlinkoOutcomeCodec {
    private const val SCHEMA_VERSION = 2
    private const val LEGACY_SCHEMA_VERSION = 1

    fun encode(outcome: PuppyPlinkoOutcome): String = JSONObject().apply {
        put("schemaVersion", SCHEMA_VERSION)
        put("pathRight", JSONArray().apply { outcome.pathRight.forEach(::put) })
        put(
            "bounceJitterPermille",
            JSONArray().apply { outcome.bounceJitterPermille.forEach(::put) }
        )
        put("binIndex", outcome.binIndex)
        put("multiplierHundredths", outcome.multiplierHundredths)
        put("payoutTreats", outcome.payoutTreats)
    }.toString()

    fun decodeAndValidate(raw: String?, wagerTreats: Long): PuppyPlinkoOutcome? {
        if (raw.isNullOrBlank() || !PuppyPlinkoEngine.isValidWager(wagerTreats)) return null

        return runCatching {
            val json = JSONObject(raw)
            val schema = json.getInt("schemaVersion")
            if (schema != SCHEMA_VERSION && schema != LEGACY_SCHEMA_VERSION) {
                return@runCatching null
            }

            val pathArray = json.getJSONArray("pathRight")
            if (pathArray.length() != PuppyPlinkoEngine.ROWS) return@runCatching null
            val path = List(pathArray.length()) { index ->
                pathArray.getBoolean(index)
            }

            // Schema 1 had no visual-jitter field. Zero jitter keeps old committed
            // rounds recoverable without changing their original result or payout.
            val jitter = if (schema == SCHEMA_VERSION) {
                val jitterArray = json.getJSONArray("bounceJitterPermille")
                if (jitterArray.length() != PuppyPlinkoEngine.ROWS) {
                    return@runCatching null
                }
                List(jitterArray.length()) { index ->
                    jitterArray.getInt(index)
                }
            } else {
                List(PuppyPlinkoEngine.ROWS) { 0 }
            }

            val expected = PuppyPlinkoEngine.outcomeForPath(
                wagerTreats = wagerTreats,
                pathRight = path,
                bounceJitterPermille = jitter
            )

            if (json.getInt("binIndex") != expected.binIndex) return@runCatching null
            if (json.getInt("multiplierHundredths") != expected.multiplierHundredths) {
                return@runCatching null
            }
            if (json.getLong("payoutTreats") != expected.payoutTreats) {
                return@runCatching null
            }

            expected
        }.getOrNull()
    }
}
